### PR TITLE
removing test and demo from ignored

### PR DESCRIPTION
**Pull request by tjsavage**
In our polymer elements, we don't typically ignore the demo, so that you can have a local element catalog.

### CODE REVIEW

**Comment by tjsavage** [comment]
@robdodson @sjmiles @atotic How do we feel about this?

**Comment by ebidel** [comment]
Maybe just remove demo? The case for keeping demo is strong, but fewer people will need /tests when using bower.

**Comment by atotic** [comment]
The problem with `ignore` is that it is absolute, there is no way to say
"install this anyway". I can see the case for using tests in production,
when you are trying to figure out why some component is failing....

**Comment by robdodson** [comment]
i'm in favor of keeping demo and ignoring tests. In the past i've jumped into local demos to see how something should work or steal the code. I can't recall a time I've actually used tests via a bower installed element

**Comment by tjsavage** [comment]
SG - I'll close this PR and open a new one just with removing test

**Pull request closed without merging**
