### PR TITLE
Update Polymer version: 1.2.0

### PR DESCRIPTION
**Pull request by abdonrd**

### CODE REVIEW

**Comment by samccone** [comment]
since we are using the ^ there is no real reason to hard lock it to only 1.2+  (if we were using some new features in 1.2 that would be a good argument for it, however we are not)

:-1: to this landing ATM

**Comment by abdonrd** [comment]
I understand, thanks @samccone!

**Comment by ebidel** [comment]
Doesn't hurt to keep things up to date. Some people aren't familiar with the versioning stufff.

**Comment by samccone** [comment]
the only impact of this change is that bower is going to complain is anyone is using 1.15 or < on any element / dependency and starts using this, there will be a new conflict to resolve, so unnecessarily locking it to the latest version may cause more headache for end users.

**Comment by ebidel** [comment]
seed-element is meant for new projects. Keeping it at HEAD is good for business. Hopefully anyone bower installing this into their existing project will be using `^` to  bring in polymer.html. If they're just using elements, that's the case already.

**Comment by samccone** [comment]
> seed-element is meant for new projects 

via yeoman el generator this seed element is used through a project life cycle / across multiple projects by end users, so "new" is relative.

Since we are using `^` bower will pull the latest semver release, imho locking it to 1.2+ is unneeded and only going to increase the potential to hit the dreaded bower resolve version conflict screen.

Ideally the version base semver range of polymer we specify here should be as low and inclusive as possible given the requirements of this element, so it is as seemelss as possible to "seed" this into any project.

**Comment by ebidel** [comment]
That's why we use `^`. It's very flexible.

**Comment by robdodson** [comment]
@samccone small correction. The yeoman el subgenerator doesn't use the seed-element project directly and doesn't stamp out anything bower related. Only `yo polymer:seed` does that, but that's not intended to be used inside a project, it's only if you're creating a standalone element that you plan to vend on GitHub. I may need to clarify the docs on that distinction.

**Pull request merged**
