### PR TITLE
add unresolved to body tag to privent FOUC

### PR DESCRIPTION
**Pull request by kzhdev**

### CODE REVIEW

**Comment by ebidel** [comment]
@addyosmani how do we set up the CLA bot on this repo?

**Comment by addyosmani** [comment]
I think we should re-check how comprehensive the current CLA bot for the org is setup. I've been getting sporadic checks on PSK PRs (e.g sometimes works https://github.com/PolymerElements/polymer-starter-kit/pull/55) so it's possible we just need to double check this is working against all repos.

**Comment by notwaldorf** [comment]
@ebidel @addyosmani according to the signers list, he's already signed it on Jun 04, 2015 (i've noticed the bot not saying anything positive sometimes in these cases), so feel free to merge this! 😊

**Comment by addyosmani** [comment]
@notwaldorf Thanks for the ping and letting us know about the CLA. Appreciate it :)

**Pull request merged**
