### PR TITLE
implement actually demo-ing the lasers

### PR DESCRIPTION
**Pull request by yufengg**
for some reason we did all this work to make lasers in seed-element but never showed off the power of the lasers...

But now this battlestation is fully operational!

### CODE REVIEW

**Comment by notwaldorf** [comment]
@addyosmani do you want to take a look at this one, please? 🍕

**Comment by yufengg** [comment]
Changed to be `console.log`

**Comment by addyosmani** [comment]
Thank you!

**Comment by yufengg** [comment]
done. Thanks for spot, twas a good one; it reads much better now.

**Comment by addyosmani** [comment]
Thanks for updating! Lgtm

**Pull request merged**
